#!/usr/bin/env bash
# Configure my domain zone:
# www --> 914-lb-01 54.237.56.89
# web-01 --> 914-web-01 100.24.74.72
# web-02 --> 914-web-02 54.146.86.214

sub_domains=( "www" "lb-01" "web-01" "web-02" )

details () {
	domain=$1
	subdomain=$2

	dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " }; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
	domain="$1"
	for i in "${sub_domains[@]}"
	do
		details "$domain" "$i"
	done
elif [ $# -eq 2 ]; then
	domain="$1"
	subdomain="$2"
	details "$domain" "$subdomain"
fi
