#!/usr/bin/env bash
#send new file to remote host}
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
#$1 = path, $2 = ip address, $3 = username
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
