#!/usr/bin/env bash
#install nginx and redirect to CADO video
new_string="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=L3G1UX_eJV0&t=758s;\n\t}\n"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "37a\ $new_string" /etc/nginx/sites-enabled/default
sudo service nginx start
