#!/usr/bin/env bash
#page 404
new_string="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=L3G1UX_eJV0&t=758s;\n\t}\n"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "37a\ $new_string" /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo service nginx start
sudo service nginx restart
