#!/usr/bin/env bash
# Serve a web page using nginx
apt update -y
apt install -y nginx

echo "Holberton School" > /var/www/html/index.html

REDIRECT="\\\trewrite ^/redirect_me https://github.com/davixcky permanent;"
sed -i "24i $REDIRECT" /etc/nginx/sites-available/default

NOT_FOUND="\\\terror_page 404 /404.html;\n\
        location = /404.html {\n\
                root /var/www/html;\n\
                internal;\
        }"
sed -i "26i $NOT_FOUND" /etc/nginx/sites-available/default

PAGE_404="Ceci n'est pas une page" 
echo "${PAGE_404}" > /var/www/html/404.html

HEADER_HOSTNAME="\\\tadd_header X-Served-By ${HOSTNAME};"
sed -i "26i $HEADER_HOSTNAME" /etc/nginx/sites-available/default

service nginx restart
