#!/usr/bin/env bash
# Setting haproxy as load balancer
sudo apt-get update
sudo apt-get -y install haproxy
printf "\nfrontend hbtn-lb\n
\tbind *:80\n
\tmode http\n
\toption forwardfor\n
\tdefault_backend servers\n\n
backend servers\n\
\tbalance roundrobin\n
\tserver [STUDENT_ID]-web-01 100.24.74.72\n
\tserver [STUDENT_ID]-web-02 54.146.86.214\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start


