#!/usr/bin/env bash
#say bad luck how in tree countries
i=1
while [ $i -le 20 ]; do
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	esac
    (( i++ ))
done
