#!/usr/bin/env bash
#print 12 hours of the day
min=1
hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    (( min = 1 ))
    while [ $min -le 59 ]; do
	echo $min
	(( min++ ))
    done
    (( hour++ ))
done
